apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: roboshop-dynamic-ebs
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: xfs
  iopsPerGB: "50"
  encrypted: "true"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true